<?php
/**
 * Invoice List Table
 *
 * @package B2Brouter\WooCommerce
 * @since 1.0.0
 */

namespace B2Brouter\WooCommerce;

if (!defined('ABSPATH')) {
    exit;
}

// Load WP_List_Table if not already loaded
if (!class_exists('WP_List_Table')) {
    require_once ABSPATH . 'wp-admin/includes/class-wp-list-table.php';
}

/**
 * Invoice_List_Table class
 *
 * Displays a list of all invoices generated by the plugin
 *
 * @since 1.0.0
 */
class Invoice_List_Table extends \WP_List_Table {

    /**
     * Settings instance
     *
     * @since 1.0.0
     * @var Settings
     */
    private $settings;

    /**
     * Invoice Generator instance
     *
     * @since 1.0.0
     * @var Invoice_Generator
     */
    private $invoice_generator;

    /**
     * Constructor
     *
     * @since 1.0.0
     * @param Settings $settings Settings instance
     * @param Invoice_Generator $invoice_generator Invoice generator instance
     */
    public function __construct(Settings $settings, Invoice_Generator $invoice_generator) {
        $this->settings = $settings;
        $this->invoice_generator = $invoice_generator;

        parent::__construct(array(
            'singular' => __('Invoice', 'b2brouter-woocommerce'),
            'plural'   => __('Invoices', 'b2brouter-woocommerce'),
            'ajax'     => false,
        ));
    }

    /**
     * Get columns
     *
     * @since 1.0.0
     * @return array Column names
     */
    public function get_columns() {
        return array(
            'cb'             => '<input type="checkbox" />',
            'order_number'   => __('Order #', 'b2brouter-woocommerce'),
            'customer'       => __('Customer', 'b2brouter-woocommerce'),
            'invoice_number' => __('Invoice #', 'b2brouter-woocommerce'),
            'date'           => __('Date', 'b2brouter-woocommerce'),
            'status'         => __('Status', 'b2brouter-woocommerce'),
            'amount'         => __('Amount', 'b2brouter-woocommerce'),
            'actions'        => __('Actions', 'b2brouter-woocommerce'),
        );
    }

    /**
     * Get sortable columns
     *
     * @since 1.0.0
     * @return array Sortable column names
     */
    public function get_sortable_columns() {
        return array(
            'order_number' => array('ID', false),
            'date'         => array('date', true), // true = already sorted
        );
    }

    /**
     * Get bulk actions
     *
     * @since 1.0.0
     * @return array Bulk actions
     */
    public function get_bulk_actions() {
        return array(
            'download' => __('Download PDFs', 'b2brouter-woocommerce'),
        );
    }

    /**
     * Prepare items for display
     *
     * @since 1.0.0
     * @return void
     */
    public function prepare_items() {
        $columns  = $this->get_columns();
        $hidden   = array();
        $sortable = $this->get_sortable_columns();

        $this->_column_headers = array($columns, $hidden, $sortable);

        // Handle bulk actions
        $this->process_bulk_action();

        // Get pagination parameters
        $per_page     = 20;
        $current_page = $this->get_pagenum();
        $offset       = ($current_page - 1) * $per_page;

        // Get sorting parameters
        $orderby = isset($_REQUEST['orderby']) ? sanitize_text_field($_REQUEST['orderby']) : 'date';
        $order   = isset($_REQUEST['order']) ? sanitize_text_field($_REQUEST['order']) : 'DESC';

        // Query orders with invoices
        $args = array(
            'limit'      => $per_page,
            'offset'     => $offset,
            'orderby'    => $orderby,
            'order'      => $order,
            'meta_key'   => '_b2brouter_invoice_id',
            'meta_compare' => 'EXISTS',
            'type'       => array('shop_order', 'shop_order_refund'),
        );

        $orders = wc_get_orders($args);

        // Get total count for pagination
        $total_args = array(
            'limit'      => -1,
            'meta_key'   => '_b2brouter_invoice_id',
            'meta_compare' => 'EXISTS',
            'type'       => array('shop_order', 'shop_order_refund'),
            'return'     => 'ids',
        );
        $total_items = count(wc_get_orders($total_args));

        // Prepare items
        $this->items = $orders;

        // Set pagination
        $this->set_pagination_args(array(
            'total_items' => $total_items,
            'per_page'    => $per_page,
            'total_pages' => ceil($total_items / $per_page),
        ));
    }

    /**
     * Column default
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @param string $column_name Column name
     * @return string Column output
     */
    protected function column_default($order, $column_name) {
        switch ($column_name) {
            case 'order_number':
            case 'customer':
            case 'invoice_number':
            case 'date':
            case 'status':
            case 'amount':
            case 'actions':
                $method = 'column_' . $column_name;
                if (method_exists($this, $method)) {
                    return $this->$method($order);
                }
                return '';
            default:
                return '';
        }
    }

    /**
     * Checkbox column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Checkbox HTML
     */
    protected function column_cb($order) {
        return sprintf(
            '<input type="checkbox" name="invoice[]" value="%s" />',
            esc_attr($order->get_id())
        );
    }

    /**
     * Order number column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Order number with link
     */
    protected function column_order_number($order) {
        $order_id = $order->get_id();
        $is_refund = $order->get_type() === 'shop_order_refund';

        if ($is_refund) {
            $parent_order = wc_get_order($order->get_parent_id());
            if ($parent_order) {
                $parent_edit_url = get_edit_post_link($parent_order->get_id());
                return sprintf(
                    '<a href="%s"><strong>%s</strong></a><br><small>%s #%s</small>',
                    esc_url($parent_edit_url),
                    esc_html__('Refund', 'b2brouter-woocommerce'),
                    esc_html__('for Order', 'b2brouter-woocommerce'),
                    esc_html($parent_order->get_order_number())
                );
            }
        }

        $edit_url = get_edit_post_link($order_id);
        $order_number = $order->get_order_number();
        return sprintf(
            '<a href="%s"><strong>#%s</strong></a>',
            esc_url($edit_url),
            esc_html($order_number)
        );
    }

    /**
     * Customer column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Customer name and email
     */
    protected function column_customer($order) {
        // For refunds, get customer info from parent order
        if ($order->get_type() === 'shop_order_refund') {
            $parent_order = wc_get_order($order->get_parent_id());
            if ($parent_order) {
                $order = $parent_order;
            }
        }

        $customer_name = '';

        if ($order->get_billing_first_name() || $order->get_billing_last_name()) {
            $customer_name = trim($order->get_billing_first_name() . ' ' . $order->get_billing_last_name());
        }

        if (empty($customer_name)) {
            $customer_name = $order->get_billing_company();
        }

        if (empty($customer_name)) {
            $customer_name = __('Guest', 'b2brouter-woocommerce');
        }

        $customer_email = $order->get_billing_email();

        if ($customer_email) {
            return sprintf(
                '%s<br><small><a href="mailto:%s">%s</a></small>',
                esc_html($customer_name),
                esc_attr($customer_email),
                esc_html($customer_email)
            );
        }

        return esc_html($customer_name);
    }

    /**
     * Invoice number column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Invoice number with B2Brouter link
     */
    protected function column_invoice_number($order) {
        $invoice_id = $order->get_meta('_b2brouter_invoice_id');
        $invoice_number = Invoice_Generator::get_formatted_invoice_number($order);

        if (empty($invoice_id)) {
            return '<span style="color: #999;">—</span>';
        }

        $web_app_base_url = $this->settings->get_web_app_base_url();
        $b2brouter_url = $web_app_base_url . '/invoices/' . esc_attr($invoice_id);

        return sprintf(
            '<a href="%s" target="_blank" title="%s">%s <span class="dashicons dashicons-external" style="font-size: 12px; text-decoration: none;"></span></a>',
            esc_url($b2brouter_url),
            esc_attr__('View in B2Brouter', 'b2brouter-woocommerce'),
            esc_html($invoice_number)
        );
    }

    /**
     * Date column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Formatted date
     */
    protected function column_date($order) {
        $date_created = $order->get_date_created();

        if (!$date_created) {
            return '—';
        }

        return sprintf(
            '%s<br><small>%s</small>',
            esc_html($date_created->date_i18n(get_option('date_format'))),
            esc_html($date_created->date_i18n(get_option('time_format')))
        );
    }

    /**
     * Status column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Status badge
     */
    protected function column_status($order) {
        $status = $order->get_meta('_b2brouter_invoice_status');

        if (empty($status)) {
            $status = 'pending';
        }

        return sprintf(
            '<span class="b2brouter-status-badge status-%s">%s</span>',
            esc_attr($status),
            esc_html(ucfirst($status))
        );
    }

    /**
     * Amount column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Formatted amount
     */
    protected function column_amount($order) {
        return wc_price($order->get_total());
    }

    /**
     * Actions column
     *
     * @since 1.0.0
     * @param \WC_Order $order Order object
     * @return string Action buttons
     */
    protected function column_actions($order) {
        $order_id = $order->get_id();

        $actions = array();

        // View PDF button
        $actions[] = sprintf(
            '<button type="button" class="button button-small b2brouter-list-view-pdf" data-order-id="%d" title="%s">
                <span class="dashicons dashicons-pdf" style="line-height: 1.4;"></span> %s
            </button>',
            esc_attr($order_id),
            esc_attr__('View PDF', 'b2brouter-woocommerce'),
            esc_html__('View', 'b2brouter-woocommerce')
        );

        // Download PDF button
        $actions[] = sprintf(
            '<button type="button" class="button button-small b2brouter-list-download-pdf" data-order-id="%d" title="%s">
                <span class="dashicons dashicons-download" style="line-height: 1.4;"></span> %s
            </button>',
            esc_attr($order_id),
            esc_attr__('Download PDF', 'b2brouter-woocommerce'),
            esc_html__('Download', 'b2brouter-woocommerce')
        );

        return implode(' ', $actions);
    }

    /**
     * Process bulk actions
     *
     * @since 1.0.0
     * @return void
     */
    public function process_bulk_action() {
        if ('download' === $this->current_action()) {
            // Check nonce
            if (!isset($_REQUEST['_wpnonce']) || !wp_verify_nonce($_REQUEST['_wpnonce'], 'bulk-' . $this->_args['plural'])) {
                wp_die(__('Security check failed', 'b2brouter-woocommerce'));
            }

            // Get selected invoices
            $invoice_ids = isset($_REQUEST['invoice']) ? array_map('intval', $_REQUEST['invoice']) : array();

            if (empty($invoice_ids)) {
                return;
            }

            // For now, we'll handle bulk download via JavaScript
            // Add a transient to signal JS to download multiple PDFs
            set_transient('b2brouter_bulk_download_' . get_current_user_id(), $invoice_ids, 300);

            // Redirect back with a success notice
            $redirect_url = add_query_arg(
                array(
                    'page' => 'b2brouter-invoices',
                    'bulk_download' => count($invoice_ids),
                ),
                admin_url('admin.php')
            );

            wp_safe_redirect($redirect_url);
            exit;
        }
    }

    /**
     * Display bulk download notice
     *
     * @since 1.0.0
     * @return void
     */
    public function bulk_download_notice() {
        if (isset($_GET['bulk_download'])) {
            $count = intval($_GET['bulk_download']);
            printf(
                '<div class="notice notice-success is-dismissible"><p>%s</p></div>',
                sprintf(
                    esc_html(_n(
                        'Preparing to download %d invoice PDF.',
                        'Preparing to download %d invoice PDFs.',
                        $count,
                        'b2brouter-woocommerce'
                    )),
                    $count
                )
            );
        }
    }

    /**
     * Message to display when no items found
     *
     * @since 1.0.0
     * @return void
     */
    public function no_items() {
        esc_html_e('No invoices found.', 'b2brouter-woocommerce');
    }
}
